<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "janolawservice"
 *
 * Auto generated by Extension Builder 2016-04-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'janolaw Service',
    'description' => 'Integriert janolaw Service',
    'category' => 'plugin',
    'author' => 'janolaw AG',
    'author_email' => 'hlinneweber@janolaw.de',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '10.0.0-11.5.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
