<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "janolawservice"
 *
 * Auto generated by Extension Builder 2016-04-27
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'janolaw Service',
	'description' => 'Integriert janolaw Service',
	'category' => 'plugin',
	'author' => 'janolaw AG',
	'author_email' => 'hlinneweber@janolaw.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.3',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);